/**
 * Port Configuration (Auto-generated from ports.ts)
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY! 
 * ⚠️  This is auto-generated from config/ports.ts for CommonJS compatibility
 * ⚠️  Edit config/ports.ts instead and regenerate this file
 *
 * AI-NOTE: This file exists only for next.config.js CommonJS compatibility.
 * Always edit the TypeScript source: config/ports.ts
 */

// This should be generated from ports.ts via build script
const PORTS = {
  DEV: 3002,
  E2E: 3009, 
  PRODUCTION: process.env.PORT || 3000,
  FIREBASE_AUTH: 9099,
  FIREBASE_FIRESTORE: 8080,
  FIREBASE_STORAGE: 9199,
};

module.exports = { PORTS };