name: CI Pipeline (Optimized)

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '10'
  # WSL2-optimized settings for Vitest
  VITEST_POOL: 'forks'
  # Let Vitest auto-optimize thread count based on CI runner

jobs:
  # Single job for dependency installation and caching
  setup:
    name: Setup & Cache Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-key }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Cache node_modules
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile

  # Parallel linting and type checking
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Run ESLint
      run: pnpm run lint

    - name: Run TypeScript compiler check
      run: pnpm exec tsc --noEmit

    - name: Check for duplicate components
      run: pnpm run check-duplicates

  # Project-based test execution
  test:
    name: Tests - ${{ matrix.project }}
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        project: [chess-core, tablebase, training, move-quality, shared]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Run tests for ${{ matrix.project }}
      run: |
        # Run project-specific tests using workspace config
        pnpm exec vitest --workspace vitest.workspace.ts run \
          --project ${{ matrix.project }} \
          --coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.project }}
        path: coverage/
      if: always()

  # Merge coverage reports
  coverage:
    name: Merge Coverage Reports
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all coverage reports
      uses: actions/download-artifact@v4
      with:
        pattern: coverage-report-*
        merge-multiple: true

    - name: Merge coverage reports
      run: |
        echo "Coverage reports merged"

  # Integration tests (including shared and cross-feature tests)
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Run integration tests
      run: |
        # Run integration project from workspace
        pnpm exec vitest --workspace vitest.workspace.ts run \
          --project integration
      env:
        CI: true

  # Firebase Integration Tests with Emulator Pre-warming  
  firebase-tests:
    name: Firebase Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Firebase CLI
      run: pnpm add -g firebase-tools

    - name: Start Firebase Emulators
      run: |
        echo "Starting Firebase emulators in background..."
        firebase emulators:start --only firestore,auth --project demo-chess &
        FIREBASE_PID=$!
        echo "FIREBASE_PID=$FIREBASE_PID" >> $GITHUB_ENV
        
        # Wait for emulator to be ready
        echo "Waiting for Firebase emulators to start..."
        for i in {1..30}; do
          if curl -f http://localhost:8080 > /dev/null 2>&1; then
            echo "✅ Firebase emulator is ready!"
            break
          fi
          echo "⏳ Attempt $i/30 - waiting for emulator..."
          sleep 2
        done
        
        # Final health check
        if ! curl -f http://localhost:8080 > /dev/null 2>&1; then
          echo "❌ Firebase emulator failed to start within 60 seconds"
          exit 1
        fi
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Run Firebase Integration Tests
      run: |
        # Run Firebase integration tests with Vitest
        pnpm test src/tests/integration/firebase
      env:
        NODE_ENV: test
        FIRESTORE_EMULATOR_HOST: localhost:8080
        FIREBASE_AUTH_EMULATOR_HOST: localhost:9099

    - name: Stop Firebase Emulators
      if: always()
      run: |
        if [ ! -z "$FIREBASE_PID" ]; then
          kill $FIREBASE_PID || true
        fi
        pkill -f "firebase emulators" || true
        # Add actual merge logic here if needed

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        lcov-file: ./coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
        title: Unit Test Coverage Report
      continue-on-error: true


  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: setup
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Cache Next.js build
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

    - name: Build Next.js app
      run: pnpm run build
      env:
        NEXT_PUBLIC_STOCKFISH_PATH: /stockfish/

    - name: Verify build output
      run: |
        if [ ! -d ".next" ] || [ -z "$(ls -A .next)" ]; then
          echo "Error: Build output directory .next/ is missing or empty."
          echo "Build command completed but produced no artifacts."
          exit 1
        fi
        echo "✅ Build output verified: .next/ directory contains files"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: .next/
        include-hidden-files: true
        if-no-files-found: error
        retention-days: 1
      if: success()

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, test, build]
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .next/

    - name: Run Playwright tests
      run: pnpm run test:e2e
      env:
        PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 3

  quality-gates:
    name: Quality Gates Summary
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, test, integration-tests, firebase-tests, build, e2e]
    if: always()
    
    steps:
    - name: Check job statuses
      run: |
        echo "## CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ needs.lint-and-typecheck.result }}" == "success" ]; then
          echo "✅ Lint & Type Check: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Lint & Type Check: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.test.result }}" == "success" ]; then
          echo "✅ Feature Tests: Passed (5 projects)" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Feature Tests: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.integration-tests.result }}" == "success" ]; then
          echo "✅ Integration Tests: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Integration Tests: Failed" >> $GITHUB_STEP_SUMMARY
        fi

        if [ "${{ needs.firebase-tests.result }}" == "success" ]; then
          echo "✅ Firebase Tests: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Firebase Tests: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.build.result }}" == "success" ]; then
          echo "✅ Build: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Build: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.e2e.result }}" == "success" ]; then
          echo "✅ E2E Tests: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ E2E Tests: Failed" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Set final status
      if: |
        needs.lint-and-typecheck.result == 'failure' ||
        needs.test.result == 'failure' ||
        needs.integration-tests.result == 'failure' ||
        needs.firebase-tests.result == 'failure' ||
        needs.build.result == 'failure' ||
        needs.e2e.result == 'failure'
      run: |
        echo "❌ Quality gates failed. Please fix the issues before merging."
        exit 1