name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

env:
  NODE_VERSION: '20'

jobs:
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run TypeScript compiler check
      run: npx tsc --noEmit

    - name: Check for duplicate components
      run: npm run check-duplicates

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests with coverage
      run: npm test -- --testPathPattern=tests/unit --coverage --coverageDirectory=coverage/unit

    - name: Upload unit test coverage
      uses: actions/upload-artifact@v4
      with:
        name: unit-coverage
        path: coverage/unit

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        lcov-file: ./coverage/unit/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
        title: Unit Test Coverage Report

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run integration tests
      run: npm test -- --testPathPattern=tests/integration --coverage --coverageDirectory=coverage/integration

    - name: Upload integration test coverage
      uses: actions/upload-artifact@v4
      with:
        name: integration-coverage
        path: coverage/integration

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js app
      run: npm run build

    - name: Check build output
      run: |
        echo "Build completed successfully"
        ls -la .next/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: .next/
        retention-days: 1

  coverage-report:
    name: Coverage Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download unit coverage
      uses: actions/download-artifact@v4
      with:
        name: unit-coverage
        path: coverage/unit

    - name: Download integration coverage
      uses: actions/download-artifact@v4
      with:
        name: integration-coverage
        path: coverage/integration

    - name: Merge coverage reports
      run: |
        npm install -g nyc
        mkdir -p coverage/combined
        nyc merge coverage coverage/combined/coverage.json
        nyc report --reporter=lcov --reporter=text --report-dir=coverage/combined

    - name: Check coverage thresholds
      run: |
        COVERAGE=$(nyc report --reporter=json-summary --report-dir=coverage/combined | jq '.total.statements.pct')
        echo "Total coverage: $COVERAGE%"
        
        # Goal is 80% coverage
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "⚠️ Coverage is below 80% threshold"
          exit 1
        else
          echo "✅ Coverage meets threshold"
        fi

  quality-gates:
    name: Quality Gates Summary
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, unit-tests, integration-tests, build]
    if: always()
    
    steps:
    - name: Check job statuses
      run: |
        echo "## CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ needs.lint-and-typecheck.result }}" == "success" ]; then
          echo "✅ Lint & Type Check: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Lint & Type Check: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.unit-tests.result }}" == "success" ]; then
          echo "✅ Unit Tests: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Unit Tests: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.integration-tests.result }}" == "success" ]; then
          echo "✅ Integration Tests: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Integration Tests: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.build.result }}" == "success" ]; then
          echo "✅ Build: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Build: Failed" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Set final status
      if: |
        needs.lint-and-typecheck.result != 'success' ||
        needs.unit-tests.result != 'success' ||
        needs.integration-tests.result != 'success' ||
        needs.build.result != 'success'
      run: |
        echo "❌ Quality gates failed. Please fix the issues before merging."
        exit 1